# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180803_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='是否新品'),
        ),
    ]
